[pve]
10.125.128.253

[workers]
192.168.200.2
192.168.200.3
192.168.200.4

[load_balancer]
192.168.200.5

[pve:vars]
ansible_user=root

[workers:vars]
ansible_user=root
ansible_ssh_common_args=-o ProxyJump=root@10.125.128.253

[load_balancer:vars]
ansible_user=root
ansible_ssh_common_args=-o ProxyJump=root@10.125.128.253
